[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/pix/charge"
  to = "/.netlify/functions/fruitfy-pix-charge"
  status = 200
  force = true

[[redirects]]
  from = "/api/order/:order"
  to = "/.netlify/functions/fruitfy-order-status?order=:order"
  status = 200
  force = true
